name: Sync Fork

on:
  schedule:
    - cron: "0 0 * * *"
  # 可以支持手动触发
  workflow_dispatch:

jobs:
  repo-sync:
    name: Repo Fork
    runs-on: ubuntu-latest
    steps:
      - uses: tgymnich/fork-sync@v1.8
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          owner: ACL4SSR # fork 的上游仓库 user
          head: master # fork 的上游仓库 branch
          base: master # 本地仓库 branch
